name: Generate ARM template & Add button

on:
  workflow_dispatch:
  push: 
    branches:
      - v3
    paths:
      - iac/**


jobs:
  generate-arm-template:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Bicep Build
        uses: Azure/bicep-build-action@v1.0.0
        with:
          bicepFilePath: 'iac/azuredeploy.bicep'
          outputFilePath: 'iac/azuredeploy.json'

      - name: push-update
        run: |
          ls -R
          git config --global user.name 'Gitub Action Bot'
          git config --global user.email 'wilfried.woivre@users.noreply.github.com'
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -am "Add Azure ARM template"
          git pull --rebase
          git push

  add-azure-deploy-button:
    needs:
      - generate-arm-template
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: rebase-before-run
      run: |
        git config --global user.name 'Gitub Action Bot'
        git config --global user.email 'wilfried.woivre@users.noreply.github.com'
        git pull --rebase

    - name: generate-deploy-button
      id: generate-deploy-button
      uses: wilfriedwoivre/action-deploy-azure-button@v1.1
      env:
        templatePath: 'iac/azuredeploy.json'
        markdownPath: 'Readme.md'
        branch: 'v3'
      

    - name: debug
      run: echo ${{ steps.generate-deploy-button.outputs.fileUpdated }}

    - name: push-update
      if: steps.generate-deploy-button.outputs.fileUpdated == 'True'
      run: |
        git config --global user.name 'Gitub Action Bot'
        git config --global user.email 'wilfried.woivre@users.noreply.github.com'
        git add .
        git diff --quiet && git diff --staged --quiet || git commit -am "Add Azure deploy button"
        git pull --rebase
        git push

